import json

with open("middle_east.ipynb", "r") as f:
    nb = json.load(f)

# Find the cell that defines df_resources (Cell 3) to see its structure.
# We will just append a new cell that augments df_resources.

new_cell_source = [
    "# ── Cell 5: 3D Production Capacity Map (PyDeck ColumnLayer) ───────────────────\n",
    "import pydeck as pdk\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "\n",
    "BAR_ELEVATION_SCALE = 3000\n",
    "LABEL_Z_OFFSET = 20000\n",
    "\n",
    "# Add a normalized capacity scale (1-100) to represent relative production size.\n",
    "# For example, Ghawar is massive (100), while smaller fields/plants get lower values.\n",
    "capacity_mapping = {\n",
    "    \"Ghawar\": 100, \"Safaniyah\": 80, \"Khurais\": 60, \"Shaybah\": 50, \"Manifa\": 50, \"Zuluf\": 45, \"Marjan\": 45,\n",
    "    \"Abqaiq\": 40, \"Berri\": 35, \"Haradh\": 30, \"Khursaniyah\": 30, \"Qatif\": 25, \"Abu Sa'fah\": 25,\n",
    "    \"Karan\": 40, \"Hasbah\": 35, \"Arabiyah\": 35, \"Jafurah\": 50, \"Midyan\": 15,\n",
    "    \"Mahd Ad Dhahab\": 20, \"Jabal Sayid\": 25, \"Al-Jalamid\": 35, \"Umm Wu'al\": 30, \"Al Ba'itha\": 30,\n",
    "    \"Ad Duwayhi\": 20, \"Bulghah\": 15, \"Al Sukhaybarat\": 15, \"Al Amar\": 15, \"Al Masane\": 15,\n",
    "    \"Sudair Solar PV\": 35, \"Sakaka Solar\": 15, \"NEOM Green H2\": 45, \"Al Shuaibah Solar\": 40, \"Ar Rass Solar\": 25,\n",
    "    \"Ras Al-Khair\": 50, \"Jubail Desal\": 40, \"Shuaiba Desal\": 35, \"Yanbu Desal\": 25,\n",
    "    \"Ras Tanura Refinery\": 60, \"Yanbu Refinery\": 45, \"Jubail Refinery\": 45, \"Jazan Refinery\": 40,\n",
    "    \"Riyadh Refinery\": 25, \"Ras Al-Khair Smelter\": 35\n",
    "}\n",
    "\n",
    "# Build a JSON-serializable copy for PyDeck. Passing the pandas DataFrame\n",
    "# directly can serialize as an empty internal manager object in newer pandas.\n",
    "df_3d = df_resources.copy()\n",
    "df_3d['capacity_scale'] = df_3d['name'].map(capacity_mapping).fillna(10).astype(float)\n",
    "df_3d['label_z'] = df_3d['capacity_scale'] * BAR_ELEVATION_SCALE + LABEL_Z_OFFSET\n",
    "df_3d['label_text'] = df_3d.apply(lambda row: f\"{row['name']}\\nOutput: {row['capacity_scale']:.0f}/100\", axis=1)\n",
    "\n",
    "# Map colors to RGB lists for PyDeck\n",
    "COLOR_MAP_RGB = {\n",
    "    \"Oil\": [218, 165, 32, 220],     # Gold/Amber\n",
    "    \"Gas\": [70, 130, 180, 220],     # Steel Blue\n",
    "    \"Mineral\": [184, 115, 51, 220],     # Copper\n",
    "    \"Solar\": [255, 200, 0, 220],      # Bright Yellow\n",
    "    \"Desalination\": [0, 191, 255, 220],      # Deep Sky Blue\n",
    "    \"Refinery\": [169, 169, 169, 220],    # Gray\n",
    "}\n",
    "\n",
    "df_3d['color_rgb'] = df_3d['type'].map(COLOR_MAP_RGB)\n",
    "df_3d['color_rgb'] = df_3d['color_rgb'].apply(lambda c: c if isinstance(c, list) else [255, 255, 255, 220])\n",
    "column_data = df_3d[\n",
    "    ['name', 'lat', 'lon', 'type', 'subtype', 'notes', 'capacity_scale', 'label_z', 'label_text', 'color_rgb']\n",
    "].to_dict('records')\n",
    "\n",
    "print(\"Building 3D ColumnLayer...\")\n",
    "\n",
    "layer_3d = pdk.Layer(\n",
    "    \"ColumnLayer\",\n",
    "    column_data,\n",
    "    get_position=[\"lon\", \"lat\"],\n",
    "    get_elevation=\"capacity_scale\",\n",
    "    elevation_scale=BAR_ELEVATION_SCALE,  # Adjust height multiplier\n",
    "    radius=12000,          # Adjust column width\n",
    "    get_fill_color=\"color_rgb\",\n",
    "    extruded=True,\n",
    "    pickable=True,\n",
    "    auto_highlight=True,\n",
    ")\n",
    "\n",
    "label_layer = pdk.Layer(\n",
    "    \"TextLayer\",\n",
    "    column_data,\n",
    "    get_position=[\"lon\", \"lat\", \"label_z\"],\n",
    "    get_text=\"label_text\",\n",
    "    get_size=9,\n",
    "    get_color=[245, 245, 245, 230],\n",
    "    get_pixel_offset=[0, -6],\n",
    "    billboard=True,\n",
    "    pickable=False,\n",
    ")\n",
    "\n",
    "view_state_3d = pdk.ViewState(\n",
    "    latitude=24.5,\n",
    "    longitude=45.0,\n",
    "    zoom=5,\n",
    "    pitch=45,  # Tilted to see 3D effect\n",
    "    bearing=0,\n",
    ")\n",
    "\n",
    "deck_3d = pdk.Deck(\n",
    "    layers=[layer_3d, label_layer],\n",
    "    initial_view_state=view_state_3d,\n",
    "    tooltip={\n",
    "        \"html\": \"<b>{name}</b><br>\" \\\n",
    "                \"Type: {type} - {subtype}<br>\" \\\n",
    "                \"Relative Capacity: {capacity_scale}/100\",\n",
    "        \"style\": {\"backgroundColor\": \"#1a1a2e\", \"color\": \"white\", \"border\": \"1px solid #daa520\"}\n",
    "    },\n",
    "    map_style=\"dark\" # Standard dark map\n",
    ")\n",
    "\n",
    "output_3d_path = \"output/middle_east_3d_bars.html\"\n",
    "output_file = Path(output_3d_path)\n",
    "deck_3d.to_html(output_3d_path)\n",
    "\n",
    "def rgb_to_hex(rgb):\n",
    "    return f\"#{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X}\"\n",
    "\n",
    "legend_items = \"\\n\".join(\n",
    "    f\"<div style='display:flex;align-items:center;gap:8px;margin:3px 0;'>\"\n",
    "    f\"<span style='width:10px;height:10px;border-radius:2px;display:inline-block;background:{rgb_to_hex(rgb)};'></span>\"\n",
    "    f\"<span>{resource_type}</span>\"\n",
    "    f\"</div>\"\n",
    "    for resource_type, rgb in COLOR_MAP_RGB.items()\n",
    ")\n",
    "legend_html = (\n",
    "    \"<div id='resource-legend' style='position:fixed;bottom:24px;left:24px;z-index:10;\"\n",
    "    \"background:rgba(12,14,24,0.9);border:1px solid rgba(218,165,32,0.75);\"\n",
    "    \"border-radius:8px;padding:10px 12px;color:#f3f4f8;font-family:Inter,Arial,sans-serif;\"\n",
    "    \"font-size:11px;line-height:1.3;box-shadow:0 8px 24px rgba(0,0,0,0.35);'>\"\n",
    "    \"<div style='font-weight:700;margin-bottom:6px;color:#ffffff;'>Resource type</div>\"\n",
    "    f\"{legend_items}\"\n",
    "    \"<div style='margin-top:8px;color:#c7cad4;font-size:10px;'>Bar height = relative production/capacity</div>\"\n",
    "    \"</div>\"\n",
    ")\n",
    "html = output_file.read_text(encoding=\"utf-8\")\n",
    "if \"</body>\" in html:\n",
    "    html = html.replace(\"</body>\", f\"{legend_html}\\n  </body>\", 1)\n",
    "else:\n",
    "    html += legend_html\n",
    "output_file.write_text(html, encoding=\"utf-8\")\n",
    "print(f\"✓ 3D Map saved to {output_3d_path}\")\n"
]

new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "pydeck_3d_cell",
    "metadata": {},
    "outputs": [],
    "source": new_cell_source
}

nb["cells"].append(new_cell)

with open("middle_east.ipynb", "w") as f:
    json.dump(nb, f, indent=1)

print("Appended Cell 5 to middle_east.ipynb")
